//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiendaInterfaz2
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    
    public partial class TICKETDETALLE
    {
        public int TicketDetalleId { get; set; }
        [ForeignKey("TicketId")]
        public Nullable<int> TicketId { get; set; }
        public Nullable<int> ProductoId { get; set; }
        public Nullable<decimal> Descuento { get; set; }
        public Nullable<decimal> Importe { get; set; }
        public Nullable<int> CantidadProductos { get; set; }
    
        public virtual PRODUCTO PRODUCTO { get; set; }
        public virtual TICKET TICKET { get; set; }
    }
}
